sonar.testExecutionReportPaths=./coverage/jest-report.xml 
sonar.javascript.lcov.reportPaths=./coverage/lcov.info 
sonar.tests=./src/ 
sonar.sources=./src/ 
sonar.test.inclusions=**/*.spec.tsx, **/*.spec.ts, **/*.spec.jsx, **/*.spec.js
sonar.projectKey=shogun-gis-client-example-plugin
sonar.host.url=https://sq.terrestris.de
